apiVersion: v2
name: traefik
description: traefik chart for Kubernetes
type: application
version: 1.0.0
appVersion: "v3.2.2"
dependencies:
  - name: traefik
    version: "38.0.1"
    repository: "https://traefik.github.io/charts"
