external:
  enabled: true
  ip: "10.0.203.101"

internal:
  enabled: true
  ip: "10.0.203.102"

certificate:
  dnsNames:
    - "*.injunweb.com"
    - "injunweb.com"
    - "*.injun.dev"
    - "injun.dev"

clusterIssuer:
  email: me@injun.dev
