longhorn:
  defaultSettings:
    defaultDataPath: /var/mnt/longhorn
    defaultDataLocality: best-effort
    replicaAutoBalance: best-effort
    defaultReplicaCount: 1

  preUpgradeChecker:
    jobEnabled: false
