vault:
  server:
    enabled: true
    readinessProbe:
      enabled: true
      path: "/v1/sys/health?standbyok=true&perfstandbyok=true&sealedcode=204&uninitcode=204"
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 10
    livenessProbe:
      enabled: false

  ui:
    enabled: true
